// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppTokenService is an autogenerated mock type for the IAppTokenService type
type AppTokenService struct {
	mock.Mock
}

// GetAppToken provides a mock function with given fields:
func (_m *AppTokenService) GetAppToken() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAppTokenService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAppTokenService creates a new instance of AppTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppTokenService(t mockConstructorTestingTNewAppTokenService) *AppTokenService {
	mock := &AppTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
