name: Use GitHub App Token
author: Heroku PE Developer Experience
description: >-
  Creates a new GitHub app token given the supplied app id, private key,
  and either the installationId or repository (e.g. heroku/some-repository) where the app is installed.
  If neither are supplied, it's assumed that the app is installed on the repository where the action is running.

inputs:
  app_id:
    description: GitHub app ID
    required: true
  private_key:
    description: GitHub access key
    required: true
  installation_id:
    description: GitHub app installation ID
    required: false
  repository:
    description: GitHub repository where the app is installed
    required: false
    default: ${{ github.repository }}

outputs:
  app_token:
    description: Generated GitHub app token

runs:
  using: node20
  main: dist/index.js
