name: Use GitHub App Token
author: Lennox McKenzie
description: Creates a new GitHub app token given the supplied app id and private key

inputs:
  app_id:
    description: GitHub app ID
    required: true
  private_key:
    description: GitHub access key
    required: true
  repository:
    description: GitHub repository where the app is installed
    required: false
    default: ${{ github.repository }}

outputs:
  app_token:
    description: Generated GitHub app token
    value: ${{ steps.get_app_token.outputs.app_token }}

runs:
  using: composite
  steps:
    - name: Determine which binary to run
      id: get_action_binary
      run: |
        LinuxARM64="linux-arm64"
        LinuxX64="linux-amd64"
        macOSARM64="darwin-arm64"
        macOSX64="darwin-amd64"
        WindowARM64="windows-arm64.exe"
        WindowX64="windows-amd64.exe"
        current_os="${{runner.os}}${{runner.arch}}"
        echo "value=${current_os}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Run the action
      id: get_app_token
      run: >
        ${{ github.action_path }}/bin/get-app-token-${{ steps.get_action_binary.value }}
        for-gh-action
        --app-id={{ inputs.app_id }}
        --private-key={{ inputs.private_key }}
        --repository={{ github.repository }}
      working-directory: ${{ github.action_path }}
      shell: bash