name: Use GitHub App Token
author: Lennox McKenzie
description: Creates a new GitHub app token given the supplied app id and private key

inputs:
  app_id:
    description: GitHub app ID
    required: true
  private_key:
    description: GitHub access key
    required: true
  repository:
    description: GitHub repository where the app is installed
    required: false
    default: ${{ github.repository }}

outputs:
  app_token:
    description: Generated GitHub app token
    value: ${{ steps.get_app_token.outputs.app_token }}

runs:
  using: composite
  steps:
    - name: Run the action
      id: get_app_token
      run: ${{ github.action_path }}/bin/main-${{ runner.os }}-${{ runner.arch }}
      working-directory: ${{ github.action_path }}
      env:
        APP_ID: ${{ inputs.app_id }}
        PRIVATE_KEY: ${{ inputs.private_key }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
      shell: bash