name: Use GitHub App Token
on:
  push:
  merge_group:

jobs:
  build_test_and_release:
    name: Build, Test, & Release
    strategy:
      matrix:
        node-version: [ 20.x ]
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
      - name: Run action
        id: get_token
        uses: ./
        with:
          app_id: ${{ secrets.HEROKU_ALL_REPO_READ_APP_ID }}
          private_key: ${{ secrets.HEROKU_ALL_REPO_READ_PRIVATE_KEY }}
          installation_id: ${{ secrets.HEROKU_ALL_REPO_READ_INSTALLATION_ID }}
      - name: Action successful
        run: |
          if [[ "${{ steps.get_token.outcome }}" == "success" && ! -z "${{ steps.get_token.outputs.app_token }}" ]]; then
            echo "✅ App token action successful!";
          else
            echo "❌ App token action failed!";
            exit 1;
          fi
