name: Use GitHub App Token
on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  build_test_and_release:
    name: Build, Test, & Release
    outputs:
      app_token: ${{ steps.get_app_token.outputs.app_token }}
    runs-on: sfdc-hk-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3
      - name: Run unit tests
        run: make test
      - name: Run build (generate precompiled binaries)
        run: make build
      - name: Git push binaries
        if: ${{ github.event_name == 'push' || github.even.pull_request.head.repo.full_name == github.repository }}
        run: |
          git add bin
          git diff-index --quiet HEAD bin && echo "👍 No changes to push!" && exit 0
          echo "Pushing changes for updated binary files..."  
          git config user.name "Continuous Integration"
          git config user.email 'heroku-production-services@salesforce.com'
          commit_message=$(cat<<EOF
          Continuous Integration Build Artifacts
          
          $(git status --porcelain --untracked-files=no bin)
          EOF
          )
          git commit -a -m "$commit_message"
          git push
      - name: Generate app token
        id: get_app_token
        uses: ./
        with:
          app_id: ${{ secrets.HEROKU_STANDARDS_APP_ID }}
          private_key: ${{ secrets.HEROKU_STANDARDS_APP_PRIVATE_KEY }}
      - name: Generated token
        run: |
          echo "Generated token: ${{ steps.get_app_token.outputs.app_token }}"
