name: Use GitHub App Token
on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  build_test_and_release:
    name: Build, Test, & Release
    outputs:
      app_token: ${{ steps.get_app_token.outputs.app_token }}
    runs-on: sfdc-hk-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run unit tests
        run: make test
      - name: Run build (generate precompiled binaries and tag)
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
        run: make build
      - name: Generate app token
        id: get_app_token
        uses: ./
        with:
          app_id: ${{ secrets.HEROKU_STANDARDS_APP_ID }}
          private_key: ${{ secrets.HEROKU_STANDARDS_APP_PRIVATE_KEY }}
      - name: Generated token
        run: |
          echo "Generated token: ${{ steps.get_app_token.outputs.app_token }}"
